-- CIRCLE MVP · run this in Supabase SQL Editor
create extension if not exists postgis;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null,
  bio text,
  avatar_url text,
  interests text[] not null default '{}',
  intent text not null default 'Platicar',
  created_at timestamptz not null default now()
);

create table if not exists public.presence (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  location geography(point, 4326) not null,
  specific_location text,
  is_available boolean not null default false,
  last_seen timestamptz not null default now()
);

create table if not exists public.social_requests (
  id bigint generated by default as identity primary key,
  sender_id uuid not null default auth.uid() references public.profiles(id) on delete cascade,
  receiver_id uuid not null references public.profiles(id) on delete cascade,
  status text not null default 'pending' check (status in ('pending','accepted','declined','cancelled')),
  created_at timestamptz not null default now(),
  constraint no_self_request check (sender_id <> receiver_id)
);

create index if not exists presence_location_gix on public.presence using gist (location);
create index if not exists presence_last_seen_idx on public.presence(last_seen desc);

alter table public.profiles enable row level security;
alter table public.presence enable row level security;
alter table public.social_requests enable row level security;

create policy "profiles readable" on public.profiles for select using (true);
create policy "users insert own profile" on public.profiles for insert with check (auth.uid() = id);
create policy "users update own profile" on public.profiles for update using (auth.uid() = id);

-- Presence can be used by the nearby RPC, but specific_location is intentionally
-- NOT returned by nearby_profiles. It should only be surfaced after consent.
create policy "presence readable" on public.presence for select using (true);
create policy "users insert own presence" on public.presence for insert with check (auth.uid() = user_id);
create policy "users update own presence" on public.presence for update using (auth.uid() = user_id);

create policy "request participants read" on public.social_requests for select using (auth.uid() in (sender_id, receiver_id));
create policy "users send requests" on public.social_requests for insert with check (auth.uid() = sender_id);
create policy "receiver updates request" on public.social_requests for update using (auth.uid() = receiver_id);

create or replace function public.nearby_profiles(user_lat double precision, user_lng double precision, radius_meters integer default 75)
returns table (
  id uuid,
  display_name text,
  bio text,
  avatar_url text,
  interests text[],
  intent text
)
language sql
security invoker
set search_path = public
as $$
  select
    p.id,
    p.display_name,
    p.bio,
    p.avatar_url,
    p.interests,
    p.intent
  from public.presence pr
  join public.profiles p on p.id = pr.user_id
  where pr.is_available = true
    and pr.last_seen > now() - interval '5 minutes'
    and (auth.uid() is null or pr.user_id <> auth.uid())
    and ST_DWithin(pr.location, ST_SetSRID(ST_MakePoint(user_lng, user_lat),4326)::geography, radius_meters)
  order by pr.last_seen desc
  limit 20;
$$;

-- Returns the other participant's optional location reference only after
-- the request has been accepted. This is intentionally separate from nearby_profiles.
create or replace function public.accepted_specific_location(request_id bigint)
returns text
language sql
security invoker
set search_path = public
as $$
  select pr.specific_location
  from public.social_requests sr
  join public.presence pr
    on pr.user_id = case when auth.uid() = sr.sender_id then sr.receiver_id else sr.sender_id end
  where sr.id = request_id
    and sr.status = 'accepted'
    and auth.uid() in (sr.sender_id, sr.receiver_id)
  limit 1;
$$;
